# These are supported funding model platforms

github: [mattrheault] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
tidelift: # Replace with a Tidelift platform-name/package-name e.g., npm/babel
open_collective: # Replace with a single Open Collective username e.g., opencollective
ko_fi: # Replace with a single Ko-fi username e.g., user
tide: # Replace with a single Tide username e.g., user
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username e.g., user
issuehunt: # Replace with a single IssueHunt username e.g., user
otechie: # Replace with a single Otechie username e.g., user
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2', 'link3', 'link4']
